#!/bin/bash
# Umount-EFI
# Copyright (c) 2019, 2024 chris1111. All Right Reserved
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
PARENTDIR=$(dirname "$0")
cd "$PARENTDIR"

  if [ -d "/Volumes/EFI" ]; then
    diskutil unmount "/Volumes/EFI"
  fi

  if [ -d "/Volumes/ESP" ]; then
    diskutil unmount "/Volumes/ESP"
  fi

  if [ -d "/Volumes/EFI 1" ]; then
    diskutil unmount "/Volumes/EFI 1"
  fi

  if [ -d "/Volumes/EFI 2" ]; then
    diskutil unmount "/Volumes/EFI 2"
  fi

  if [ -d "/Volumes/EFI 3" ]; then
    diskutil unmount "/Volumes/EFI 3"
  fi

  if [ -d "/Volumes/EFI 4" ]; then
    diskutil unmount "/Volumes/EFI 4"
  fi

  if [ -d "/Volumes/EFI 5" ]; then
    diskutil unmount "/Volumes/EFI 5"
  fi
  osascript -e 'do shell script "afplay './VolumeUnmount.aiff' &> /dev/null &"'

